version: '3'
services:
  grafana:
    image: grafana/grafana:7.5.17
    ports:
      - 3000:3000
    user: root
    depends_on:
      - influxdb
    volumes:
      - $PWD/dashboards:/var/lib/grafana/dashboards:ro
      - $PWD/provisioning/:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
  influxdb:
    image: influxdb:1.7
    ports:
      - 8086:8086
    user: root
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpass
      - INFLUXDB_REPORTING_DISABLED=true
  telegraf:
    image: vsananalytics/telegraf-vsan:0.0.7
    user: root
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - $PWD/certificates:/root/certificates:ro
    depends_on:
      - influxdb
